# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caf13156e4601ef1af05231be1f5f7d2e120a1a9e8a50891c044e7a602f3156aeb89b4825f53a466c6fb40a02a1dfcbd356320d1c5b6f105e4f6f3d650bfcec4

test:
  secret_key_base: 93c83477dd1e66be9233b4f43ad6013cbd2011c85f068992af1edd4c476b7e71f07147544a4ad36303fca34776844f2b4afb8e3e6aaf692fb4ee95dc9ca6be67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
